default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  passwod:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: APPNAME_development

test:
  <<: *default
  database: APPNAME_test

production:
  <<: *default
  database: APPNAME_production
  password: <%= ENV['ENVNAME_DATABASE_PASSWORD'] %>
