development:
  adapter: mysql2
  encoding: utf8
  database: APPNAME_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: APPNAME_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: APPNAME_production
  pool: 5
  username: root
  password:
